### ISSUE TITLE
missing config files

### ISSUE THREAD

**Issue by HaixiaChai** [UKPLab/aaai2019-coala-cqa-answer-selection#1]
Hi Andreas,

I am trying to reoccur the results of Table 2.  But I found the config files of CNN and p-mean Embeddings for Travel, Cooking, Apple and Aviation, which I concern, are not available. Could you let me know how can I get them, please?

Also, the results that I produced by using se_apple_attention_lstm.yaml and se_cooking_coala_pmeans.yaml are not the same as what the paper presented. They are 4.72 and 1.01... Are you sure the parameters are correct in those two files?

Thanks a lot.

Haixia

**Comment by arueckle** [comment]
That’s interesting! With performance scores close to 1.0 the model has not learned anything (1.0 would be the random performance). Maybe you can change some hyperparameters and see whether that changes?

I’ll add the hyperparamer files for cnn and pmeans on Monday.

**Comment by arueckle** [comment]
I located the configs in some old backups and added them. For the PMeans sentence embeddings, you'd need to create some new configs according to
https://github.com/UKPLab/aaai2019-coala-cqa-answer-selection#running-sentence-embedding-baselines

**Comment by HaixiaChai** [comment]
Thanks for your help. I will have a look at sentence embedding models.
